name: sdc3a
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.5
  - matplotlib
  - astropy
  - scipy
  - pip:
      - pandas==2.0.2
      - ps_eor
      - GPy
      - git+https://github.com/PolyChord/PolyChordLite@master
      - anesthetic
